import {
  DEFAULT_PARAMETERS,
  type BallParameters,
  type BallTemplate,
} from "../geometry/types";

export interface BallTemplateDefinition {
  id: BallTemplate;
  name: string;
  description: string;
  category: string;
  color: string;
  parameters: Partial<BallParameters>;
}

export const BALL_TEMPLATES: BallTemplateDefinition[] = [
  {
    id: "creative",
    name: "Full creativity",
    description: "Start from the complete airless ball editor.",
    category: "Blank canvas",
    color: "#7fa84f",
    parameters: {},
  },
  {
    id: "ping-pong",
    name: "Ping-pong",
    description: "A light shell with dense circular perforations.",
    category: "Racket sport",
    color: "#f2c900",
    parameters: {
      mode: "perforated",
      pattern: "dots",
      seamPattern: "none",
      diameter: 40,
      wallThickness: 1.25,
      featureWidth: 2.8,
      density: 2,
      quality: "standard",
    },
  },
  {
    id: "tennis",
    name: "Tennis",
    description: "Circular perforations with a continuous tennis band.",
    category: "Racket sport",
    color: "#c8ed45",
    parameters: {
      mode: "perforated",
      pattern: "dots",
      seamPattern: "tennis",
      seamOperation: "raised",
      seamWidth: 5.2,
      seamDepth: 0.3,
      seamCurvature: 50,
      diameter: 67,
      wallThickness: 1.6,
      featureWidth: 4.6,
      density: 2,
      quality: "standard",
    },
  },
  {
    id: "football",
    name: "Football",
    description: "Classic 32-panel airless football construction.",
    category: "Field sport",
    color: "#d9dbd6",
    parameters: {
      mode: "perforated",
      pattern: "hexagons",
      seamPattern: "football",
      seamOperation: "raised",
      seamWidth: 3.4,
      seamDepth: 0.3,
      diameter: 100,
      wallThickness: 1.8,
      featureWidth: 1.35,
      cellSize: 6.5,
      cellFrequency: 2,
      density: 3,
      quality: "standard",
    },
  },
  {
    id: "basketball",
    name: "Basketball",
    description: "Honeycomb shell with a traditional eight-panel layout.",
    category: "Court sport",
    color: "#d87532",
    parameters: {
      mode: "perforated",
      pattern: "hexagons",
      seamPattern: "basketball",
      seamOperation: "raised",
      seamWidth: 3,
      seamDepth: 0.3,
      seamCurvature: 50,
      wallThickness: 1.8,
      featureWidth: 1.3,
      cellSize: 6.5,
      cellFrequency: 8,
      diameter: 100,
      density: 3,
      quality: "standard",
    },
  },
  {
    id: "volleyball",
    name: "Volleyball",
    description: "Honeycomb shell divided into eighteen curved panels.",
    category: "Court sport",
    color: "#deddd7",
    parameters: {
      mode: "perforated",
      pattern: "hexagons",
      seamPattern: "volleyball",
      seamOperation: "raised",
      seamWidth: 4.2,
      seamDepth: 0.3,
      diameter: 100,
      wallThickness: 1.8,
      featureWidth: 1.35,
      cellSize: 6.5,
      cellFrequency: 8,
      density: 3,
      quality: "standard",
    },
  },
  {
    id: "baseball",
    name: "Baseball",
    description: "Round perforations with a reinforced stitched seam.",
    category: "Field sport",
    color: "#d8dad6",
    parameters: {
      mode: "perforated",
      pattern: "dots",
      seamPattern: "baseball",
      seamOperation: "raised",
      seamWidth: 5,
      seamDepth: 0.3,
      diameter: 73,
      wallThickness: 1.7,
      featureWidth: 4.4,
      density: 2,
      quality: "standard",
    },
  },
  {
    id: "golf",
    name: "Golf",
    description: "A compact airless shell with golf-like round dimples.",
    category: "Precision sport",
    color: "#dedfdb",
    parameters: {
      mode: "perforated",
      pattern: "dots",
      seamPattern: "none",
      diameter: 43,
      wallThickness: 1.4,
      featureWidth: 2.1,
      density: 3,
      quality: "standard",
    },
  },
  {
    id: "massage",
    name: "Massage ball",
    description: "A solid ball with broad pressure-point bumps.",
    category: "Body care",
    color: "#6698bd",
    parameters: {
      mode: "solid",
      pattern: "dots",
      effect: "raised",
      seamPattern: "none",
      diameter: 68,
      featureWidth: 6,
      featureHeight: 3,
      density: 2,
      quality: "standard",
    },
  },
  {
    id: "pet-toy",
    name: "Pet toy",
    description: "A solid toy concept with large rounded nubs.",
    category: "Toy",
    color: "#e5a641",
    parameters: {
      mode: "solid",
      pattern: "dots",
      effect: "raised",
      seamPattern: "none",
      diameter: 72,
      featureWidth: 7,
      featureHeight: 2.8,
      density: 2,
      quality: "standard",
    },
  },
];

export const parametersForTemplate = (
  template: BallTemplateDefinition,
  defaultBallColor: string,
): BallParameters => ({
  ...DEFAULT_PARAMETERS,
  ...template.parameters,
  template: template.id,
  ballColor:
    template.id === "creative" ? defaultBallColor : template.color,
});

export const templateById = (id: BallTemplate) =>
  BALL_TEMPLATES.find((template) => template.id === id) ?? BALL_TEMPLATES[0];
